-- =====================================================================
-- Smart Inbox Assistant — Oracle Database Schema
-- Compatible with Oracle Database 23ai / 21c / 19c
-- =====================================================================

-- 1. EMAIL Table
CREATE TABLE EMAIL (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id      VARCHAR2(255) NOT NULL,
    sender_email    VARCHAR2(255) NOT NULL,
    subject         VARCHAR2(500),
    body            CLOB,
    received_at     TIMESTAMP,
    ingested_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status          VARCHAR2(50) DEFAULT 'RECEIVED' NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_email_message_id UNIQUE (message_id)
);

CREATE INDEX idx_email_status ON EMAIL(status);
CREATE INDEX idx_email_received_at ON EMAIL(received_at);

-- 2. ATTACHMENT Table
CREATE TABLE ATTACHMENT (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_id          NUMBER NOT NULL,
    filename          VARCHAR2(255) NOT NULL,
    content_type      VARCHAR2(100),
    file_size         NUMBER,
    storage_reference VARCHAR2(500),
    sha256_hash       VARCHAR2(64),
    is_pdf            NUMBER(1) DEFAULT 0 NOT NULL,
    status            VARCHAR2(50) DEFAULT 'RECEIVED' NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_attachment_email FOREIGN KEY (email_id) REFERENCES EMAIL(id) ON DELETE CASCADE
);

CREATE INDEX idx_attachment_email_id ON ATTACHMENT(email_id);
CREATE INDEX idx_attachment_sha256 ON ATTACHMENT(sha256_hash);
CREATE INDEX idx_attachment_status ON ATTACHMENT(status);

-- 3. PROCESSING_JOB Table
CREATE TABLE PROCESSING_JOB (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attachment_id  NUMBER NOT NULL,
    status         VARCHAR2(50) DEFAULT 'QUEUED' NOT NULL,
    retry_count    NUMBER DEFAULT 0 NOT NULL,
    max_retries    NUMBER DEFAULT 3 NOT NULL,
    queued_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    started_at     TIMESTAMP,
    completed_at   TIMESTAMP,
    error_code     VARCHAR2(100),
    error_message  VARCHAR2(2000),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_job_attachment FOREIGN KEY (attachment_id) REFERENCES ATTACHMENT(id) ON DELETE CASCADE
);

CREATE INDEX idx_job_attachment_id ON PROCESSING_JOB(attachment_id);
CREATE INDEX idx_job_status ON PROCESSING_JOB(status);

-- 4. AUDIT_LOG Table
CREATE TABLE AUDIT_LOG (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_id   NUMBER,
    job_id     NUMBER,
    actor_type VARCHAR2(50) NOT NULL,
    actor_id   VARCHAR2(100),
    action     VARCHAR2(100) NOT NULL,
    old_value  CLOB,
    new_value  CLOB,
    metadata   CLOB,
    timestamp  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_email FOREIGN KEY (email_id) REFERENCES EMAIL(id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_job FOREIGN KEY (job_id) REFERENCES PROCESSING_JOB(id) ON DELETE SET NULL
);

CREATE INDEX idx_audit_email_id ON AUDIT_LOG(email_id);
CREATE INDEX idx_audit_job_id ON AUDIT_LOG(job_id);
CREATE INDEX idx_audit_action ON AUDIT_LOG(action);
CREATE INDEX idx_audit_timestamp ON AUDIT_LOG(timestamp);

-- 5. AI_RESULT Table (Prepared for Module 2)
CREATE TABLE AI_RESULT (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id         NUMBER NOT NULL,
    email_id       NUMBER NOT NULL,
    model_name     VARCHAR2(100) NOT NULL,
    model_version  VARCHAR2(50),
    prompt_version VARCHAR2(50),
    summary        CLOB,
    relevant       NUMBER(1) DEFAULT 1 NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_ai_result_job FOREIGN KEY (job_id) REFERENCES PROCESSING_JOB(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_result_email FOREIGN KEY (email_id) REFERENCES EMAIL(id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_result_job_id ON AI_RESULT(job_id);
CREATE INDEX idx_ai_result_email_id ON AI_RESULT(email_id);

-- 6. CLASSIFICATION Table (Multi-label)
CREATE TABLE CLASSIFICATION (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_result_id NUMBER NOT NULL,
    category     VARCHAR2(50) NOT NULL,
    confidence   NUMBER(5, 4) NOT NULL,
    reason       VARCHAR2(2000),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_class_ai_result FOREIGN KEY (ai_result_id) REFERENCES AI_RESULT(id) ON DELETE CASCADE
);

CREATE INDEX idx_class_ai_result_id ON CLASSIFICATION(ai_result_id);
CREATE INDEX idx_class_category ON CLASSIFICATION(category);

-- 7. EXTRACTED_FIELD Table
CREATE TABLE EXTRACTED_FIELD (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_result_id NUMBER NOT NULL,
    field_group  VARCHAR2(100) NOT NULL,
    field_name   VARCHAR2(100) NOT NULL,
    field_value  VARCHAR2(2000) NOT NULL,
    confidence   NUMBER(5, 4) NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_field_ai_result FOREIGN KEY (ai_result_id) REFERENCES AI_RESULT(id) ON DELETE CASCADE
);

CREATE INDEX idx_field_ai_result_id ON EXTRACTED_FIELD(ai_result_id);
CREATE INDEX idx_field_name ON EXTRACTED_FIELD(field_name);

-- 8. SOURCE_REFERENCE Table
CREATE TABLE SOURCE_REFERENCE (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extracted_field_id NUMBER NOT NULL,
    source_type        VARCHAR2(50) NOT NULL,
    email_id           NUMBER,
    attachment_id      NUMBER,
    page_number        NUMBER,
    text_snippet       VARCHAR2(2000),
    location           VARCHAR2(255),
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_source_field FOREIGN KEY (extracted_field_id) REFERENCES EXTRACTED_FIELD(id) ON DELETE CASCADE
);

CREATE INDEX idx_source_field_id ON SOURCE_REFERENCE(extracted_field_id);

-- 9. IMAGE_RESULT Table
CREATE TABLE IMAGE_RESULT (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_result_id    NUMBER NOT NULL,
    attachment_id   NUMBER NOT NULL,
    page_number     NUMBER NOT NULL,
    description     VARCHAR2(2000),
    confidence      NUMBER(5, 4),
    review_required NUMBER(1) DEFAULT 1 NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_image_ai_result FOREIGN KEY (ai_result_id) REFERENCES AI_RESULT(id) ON DELETE CASCADE,
    CONSTRAINT fk_image_attachment FOREIGN KEY (attachment_id) REFERENCES ATTACHMENT(id) ON DELETE CASCADE
);

CREATE INDEX idx_image_ai_result_id ON IMAGE_RESULT(ai_result_id);

-- 10. PROCESSING_METRICS Table
CREATE TABLE PROCESSING_METRICS (
    id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id                 NUMBER NOT NULL,
    total_duration_ms      NUMBER,
    extraction_duration_ms NUMBER,
    ocr_duration_ms        NUMBER,
    translation_duration_ms NUMBER,
    llm_duration_ms        NUMBER,
    validation_duration_ms NUMBER,
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_metrics_job FOREIGN KEY (job_id) REFERENCES PROCESSING_JOB(id) ON DELETE CASCADE
);

CREATE INDEX idx_metrics_job_id ON PROCESSING_METRICS(job_id);
